### ISSUE TITLE
Get the endpoint (IP) for a kafka service

### ISSUE THREAD

**Issue by pantelis-karamolegkos** [aiven/go-client-codegen#36]
## What can we help you with?

I have a `kafka` service deployed and running on Aiven. I want to get the endpoint (the IP) for this kafka service's cluster.

I have tried using the following code 

```go
		listProjectServiceTypesOut, err := aivenClient.ListProjectServiceTypes(ctx, project.ProjectName)
		if err != nil {
			fmt.Printf("error listing services for for project: %s: %s", project.ProjectName, err)
		}
```
however I get `&{Any:<nil>}` although there is definitely a kafka cluster running.

## Where would you expect to find this information?

Examples / `README.md`

**Comment by Serpentiel** [comment]
Hey, @pantelis-karamolegkos! 👋 

Thank you for bringing this up! Please try retrieving the information that you're looking for via `aivenClient.ServiceList(ctx, project.ProjectName)`.

Since methods of the client include the endpoint URL in the comment, I can recommend taking a look at https://api.aiven.io/doc/.

Additionally, each method also has a direct link to the API doc page of the specific endpoint:

https://github.com/aiven/go-client-codegen/blob/3d3e22a92161bc3d56ccda7f1b067cbbeb653554/handler/service/service.go#L123-L126

Cf. [ListProjectServiceTypes](https://api.aiven.io/doc/#tag/Service/operation/ListProjectServiceTypes) vs. [ServiceList](https://api.aiven.io/doc/#tag/Service/operation/ServiceList).

I will close this issue for now, please feel free to open it if you have any additional questions 🙂

**Comment by Serpentiel** [comment]
Related to #34.
